name: Test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
  test:

    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install cmeta
      run: python -m pip install .
    - name: Test
      run: python test.py
